### ISSUE TITLE
github.com/sap/gorfc

### ISSUE THREAD

**Issue by SimonWaldherr** [bsrdjan/ucopy#1]
Hello,

you use the package github.com/sap/gorfc, but i can't find it anywhere.
Can you help me to find it or recommend a good alternative?

Greetings
Simon

**Comment by bsrdjan** [comment]
Hi Simon,
the package is actually ready and before the initial release I planned to fix one minor bug, occuring on Windows platform. I didnt have a time for that but will start tomorrow, alao with internal release approval process. If all works well, could be released next week, with the bug fixed or with currently used workaround.
Kind regards,
Srdjan

**Comment by bsrdjan** [comment]
Btw. Is it possible to post this question in gorfc repository?

**Comment by SimonWaldherr** [comment]
Hi,
thanks for your response.
I am glad to hear that, so it will be released to public by next week.
You mention a bug, occurring on Windows, so how does it work on Unix OSes (to be concrete GNU/Linux)?
Regarding the question in your second answer: it would be, but therefore it has to be public.

Greetings,
Simon

**Comment by SimonWaldherr** [comment]
Hi Srdjan,

the repo is still private, is there any chance that it will be released to public this year?

Greets,
Simon

**Comment by SimonWaldherr** [comment]
:cry: any updates so far?

**Comment by bsrdjan** [comment]
just published, enjoy testing :smile: 
https://github.com/SAP/gorfc

**Comment by SimonWaldherr** [comment]
:smile: thanks :tada: :fireworks:
